name: Go Build and Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  build:
    name: Build and Commit Changes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures history is available for Git commands
        token: ${{ secrets.GH_PAT }}  # Uses your personal access token for checkout

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'  # Set this to the Go version you're using

    - name: Run Go Program
      run: |
        go run main.go
        # Assuming main.go outputs some files or modifies them

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update data files" || echo "No changes to commit"
        # Use the GitHub token to push changes
        git push --set-upstream origin HEAD:${{ github.ref }} --force
      env:
        GIT_AUTHOR_NAME: GitHub Action
        GIT_COMMITTER_NAME: GitHub Action
        GIT_AUTHOR_EMAIL: action@github.com
        GIT_COMMITTER_EMAIL: action@github.com
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
